array = [1,3,2,5,8,4,7,2,5,5]
print(array)
L = [3,6,7]
array.extend(L)
print(array)
array.insert(1, 33333)
print(array)
array.reverse()
print(array)
array.append(3)
print(array)
array.remove(3)
print(array)
array.sort()
print(array)
array.clear()
print(array)